#!/bin/sh

DEBIAN_TERMINFO=/lib/terminfo/l
GENTOO_TERMINFO=/etc/terminfo/l

DEST_TERMINFO=/lib/terminfo/l

if [ ! -d source$DEST_TERMINFO ]; then
    mkdir -p source$DEST_TERMINFO;
fi
cp -uv $DEBIAN_TERMINFO/linux source$DEST_TERMINFO > /dev/null 2>&1 || cp -uv $GENTOO_TERMINFO/linux source$DEST_TERMINFO > /dev/null 2>&1 || echo Error Creating Terminfo

