#!/bin/sh
export TERM=linux
mount proc /proc -t proc -n
mount sysfs /sys -t sysfs -n
#echo "0" > /proc/sys/kernel/core_uses_pid 
#echo "%e-%p.coredump" > /proc/sys/kernel/core_pattern


mount /dev/root / -o remount,rw

#mount tmpfs /mnt -t tmpfs
#cp -a /etc/zfs/* /mnt
#mount --move /mnt /etc/zfs 

mount tmpfs /mnt -t tmpfs
cp -a /dev/* /mnt
mount --move /mnt /dev



#vgscan -v
#vgchange -a y

TARGET=/var/lock
mkdir -p $TARGET
/bin/mount tmpfs $TARGET -t tmpfs -omode=1777,nodev,noexec,nosuid
mkdir -p $TARGET/zfs

TARGET=/var/run
mkdir -p $TARGET
/bin/mount tmpfs $TARGET -t tmpfs -omode=0755,nosuid
mkdir -p $TARGET/zfs


start-zfs
mkdir -p /initroot
zpool import -f initroot
/bin/sh < /dev/tty11 > /dev/tty11 2>&1 &

mkdir -p /trueshared
mkdir -p /initroot/trueshared/
/bin/mount tmpfs /trueshared -t tmpfs
/bin/mount --bind /trueshared /initroot/trueshared/

. /mount-stuff
sleep 10

#using /etc/zfs/mounts as destination for zpool import.
#not the best destination but ok for me for the time 
#being.

#umount /proc
#umount /sys

cd /initroot
#exec /sbin/chroot . /sbin/init <dev/console >dev/console  2>&1
#pivot_root . initrd
exec chroot . /sbin/init <dev/console >dev/console  2>&1

