#!/bin/sh
#/bin/mount --make-rshared /etc/zfs
#/bin/mount --bind /etc/zfs /initroot/etc/zfs



for TARGET in /var/lock /var/run; do 
  /bin/mount --make-rshared $TARGET
  mkdir -p /initroot/$TARGET
  /bin/mount --bind $TARGET /initroot$TARGET
  touch $TARGET/.ramfs
done


/bin/mount --make-rshared /dev
mkdir -p /initroot/dev-initrd
/bin/mount --bind /dev /initroot/dev-initrd

/bin/mount --make-rshared /zfs-kstat
mkdir -p /initroot/zfs-kstat
/bin/mount --bind /zfs-kstat /initroot/zfs-kstat

/bin/mount --make-rshared /sys
mkdir -p /initroot/sys
/bin/mount --bind /sys /initroot/sys

/bin/mount --make-rshared /proc
mkdir -p /initroot/proc
/bin/mount --bind /proc /initroot/proc

/bin/mount tmpfs /mounts -t tmpfs
mkdir /mounts/zfs 2>/dev/null
mkdir -p /initroot/mounts/zfs 2>/dev/null
/bin/mount --make-rshared /mounts
mkdir -p /initroot/mounts/zfs
/bin/mount  /mounts/zfs /initroot/mounts/zfs --bind

ZFSPID=`ps -e|grep zfs-fuse|head -n 1|awk '{print $1}'`
echo $ZFSPID >/initroot/var/run/sendsigs.omit
echo -17 >/proc/$ZFSPID/oom_adj

COREDEST=/var/tmp/coredump

echo "0" > /proc/sys/kernel/core_uses_pid 
echo "$COREDEST/%e-u%u-g%g-s%s-p%p.coredump" > /proc/sys/kernel/core_pattern
mount --bind  $COREDEST /initroot$COREDEST 
chmod 777 /initroot$COREDEST


cat /proc/mounts >/initroot/etc/mtab
rm /etc/mtab
ln -s /initroot/etc/mtab /etc/



